import { supabase } from "@/lib/supabase";
import { Text, Box } from "@chakra-ui/react";
import Head from "next/head";

export default function Home({ contents }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        {contents.map((c) => (
          <Text key={c.id}>{c.title}</Text>
        ))}
      </Box>
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await supabase
    .from("contents")
    .select("id, title, img")
    .order("title");

  return {
    props: {
      contents: data,
    },
  };
}
