import { Box } from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const MainLayout = ({ children, router }) => {
  return (
    <Box as="main">
      <Head>
        <title>Galiseries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar path={router.asPath} />
      <Box paddingX={10} pt={16}>
        {children}
      </Box>
    </Box>
  );
};

export default MainLayout;
